ci/cd

diff --git a/.github/workflows/run-tests.yml b/.github/workflows/run-tests.yml
--- a/.github/workflows/run-tests.yml
+++ b/.github/workflows/run-tests.yml
@@ -51,6 +51,18 @@ jobs:
           echo "$ANDROID_HOME/emulator" >> $GITHUB_PATH
           echo "$ANDROID_HOME/platform-tools" >> $GITHUB_PATH
 
+      - name: Copy APK
+        run: |
+          echo "📦 Checking for General-Store.apk..."
+          if [ -f "$PWD/General-Store.apk" ]; then
+            cp "$PWD/General-Store.apk" "/tmp/General-Store.apk"
+            chmod 644 "/tmp/General-Store.apk"
+            echo "APK_PATH=/tmp/General-Store.apk" >> $GITHUB_ENV
+          else
+            echo "❌ APK not found!"
+            exit 1
+          fi
+
       - name: Move APK to tmp for Appium
         run: |
           [ -f "$PWD/General-Store.apk" ] && echo "✅ Found APK" && cp "$PWD/General-Store.apk" "/tmp/General-Store.apk" && chmod 644 "/tmp/General-Store.apk" && echo "APK_PATH=/tmp/General-Store.apk" >> $GITHUB_ENV || (echo "❌ APK not found" && exit 1)
